"""added added_by field

Revision ID: afdad2f46712
Revises: 
Create Date: 2024-04-27 18:10:16.074469

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'afdad2f46712'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_by', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.drop_column('added_by')

    # ### end Alembic commands ###
